### ISSUE TITLE
NBA.com doesn't  update the advanced stats in real time,  the project maybe not support real time analysis.

### ISSUE THREAD

**Issue by pxpwoa** [rd11490/NBA_Tutorials#1]
In FAQ of NBA.com, it says that a player or team’s base statistics are updated simultaneously with the game and in real time. The advanced stats are updated between 10-15 minutes after a game finishes.

To make the project support the real time analysis, are you concerned about changing the way of getting the players who played in a period?

**Comment by rd11490** [comment]
This is a good point, I actually changed the the way my main project does this to use the regular box score endpoint. I need to do the same for the tutorial. I'll make sure to make that change

**Comment by rd11490** [comment]
Fixed with latest merge, thanks for bringing to my attention

**Comment by pxpwoa** [comment]
Excellent！
