### ISSUE TITLE
Question: In the RAPM tutorial how do you define a possession?

### ISSUE THREAD

**Issue by samhoppen** [rd11490/NBA_Tutorials#12]
I went through the play-by-play parser tutorial to get my pbp data in a way that it's ready to calculate RAPM. But, in the RAPM tutorial you have an extra binary column for `possession` that I'm not sure how you derived. If you could share any insights on that, that'd be great!

**Comment by rd11490** [comment]
Thats a data clean up issue on my part. If you look at the input for the RAPM tutorial you'll see that every row is duplicated and then mirrored with one of the rows having 1 possession and the other having 0. This is a hold over of how my scraper pulled the data and handled the possession count. You could give every row a possession count of 1 if you follow the tutorial for parsing possessions.
