### ISSUE TITLE
The results of some games have big deviation from NBA.com and basketball-referrence.

### ISSUE THREAD

**Issue by pxpwoa** [rd11490/NBA_Tutorials#2]
As I konwed, NBA.com and basketball-reference.com have differrent way to calculate the possessions. NBA.com use the play-by-play data, and basketball-reference caclulate it from traditional box. However, results of them are very close.  The results of this project are mostly close to the NBA.com. But there are big deviation in some game. The game is such one with GAME_ID equaling to  '0021801167' .  The possession numbers of three way  are as follow:

This project: 110.5
NBA.com: 105
basketball-reference.com: 108  (score/ORtg)

I don't konw if I make some mistake in the calcullation.

**Comment by rd11490** [comment]
I'll have to look into that game and see where the difference is. I bet there is an edge case that I'm missing. Thanks for pointing it out!

**Comment by rd11490** [comment]
I just pushed a fix. I had a bug in the code checking for And-1s. I have fixed it and am now getting 105 possessions for that game.

**Comment by pxpwoa** [comment]
> I just pushed a fix. I had a bug in the code checking for And-1s. I have fixed it and am now getting 105 possessions for that game.

Excellence！！！
