### ISSUE TITLE
In some games, EVENTMSGACTIONTYPE dones't tell you if it is a player rebound or team rebound.

### ISSUE THREAD

**Issue by pxpwoa** [rd11490/NBA_Tutorials#5]
In some games, EVENTMSGACTIONTYPE don't tell you if it is a player rebound or team rebound, because EVENTMSGACTIONTYPE is always 1. 
Like '0011700070'

**Comment by rd11490** [comment]
Will look into this tonight

**Comment by rd11490** [comment]
This is already fixed, sorry I never posted
```python
def is_team_rebound(row):
    return is_rebound(row) and (row[event_subtype] == 1 or math.isnan(row[player1_team_id]))
```
