### ISSUE TITLE
Error in Python

### ISSUE THREAD

**Issue by kemmutlu** [rd11490/NBA_Tutorials#7]
hello,

i tried exactly the same as you say. i'm getting the error "NameError: name 'extract_data' is not defined".

client = urllib3.PoolManager()
season = "2019-20"

frame = extract_data(client, player_stats_url(season)) !! in this step i get the error.

am i missing something?

**Comment by rd11490** [comment]
I have rewritten the README to more accurately reflect the current form of the code. Also you can go to the link below to see the exact code.

https://github.com/rd11490/NBA_Tutorials/blob/master/finding_endpoints/download_stats_nba_data.py
